### ISSUE TITLE
the macos-def:diskutil_test should allow for checking if the owners, groups, or symlink status have changed 

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#109]
We should consider collecting the following changes to a file that may be
reported by diskutil in the macos-def:diskutil_test:

  -Checking changes in owners 
  -Checking changes in groups 
  -Checking changes in symlink status 

Please see the following oval-developer-list post for additional information.

http://making-security-measurable.1364806.n2.nabble.com/OSX-Diskutil-test-td6449835.html#a6458789

**Comment by solind** [comment]
I was going to close this thinking that the test died in OSX 10.11 with the removal of the diskutil verifyPermissions command-line option.  But then I found package verification is still possible:

http://osxdaily.com/2015/11/04/verify-repair-permissions-mac-os-x/

Shall we update the documentation to reference this capability?
