### ISSUE TITLE
for each test, document whether or not it can be assessed remotely

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#113]
We should document whether or not each test can bee assessed remotely.

Please see the following oval-developer-list post for additional information.

http://making-security-measurable.1364806.n2.nabble.com/OVAL-Malware-Artifact-Hunting-SCAP-and-Validation-tp6528622.html

**Comment by solind** [comment]
Every test can be performed remotely, except (by definition) for the process_test where pid/@xsi:nil="true".
