### ISSUE TITLE
consider revising Def, Test, Object, State, and Var identification to include version

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#115]
During the SCAP 1.2 discussion at 2011 developer days there was a bit of
discussion around the need to differentiate the core constructs of the
oval-definitions-schema by both @id and @version essentially treating the two
as a composite key. 

This modification could be made to default to the current behavior and then
allow for optional identification of specific versions of these things via all
reference structures within OVAL. This would include at least:
- criterion references to tests
- test references to objects and states
- extend_definition references to definitions
- and many others

Minimally we need to ensure that there is a better shared understanding of how
items are identified in OVAL and the tradeoffs of including the version as part
of a composite key.

**Comment by solind** [comment]
This seems like a bad idea.  Currently there's a schema restriction preventing duplicate IDs, and why would anyone ever want to run different versions of the same definition/test/object/state in the context of a single OVAL definitions file?  The version numbers are really for internal repository tracking purposes.  They could be used to create definitions files with specific artifact versions, which obviates the need to have this in the scope of an individual definitions file.

Therefore, closing.
