### ISSUE TITLE
determine if the record datatype is appropriate for the value entity in the win-def:activedirectory57_test and the ind-def:ldap57_test

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#121]
We need to determine if there really is a need to support structured data in the
value entity of the win-def:activedirectory57_test and the ind-def:ldap57_test.
Please see the following oval-developer-list post for additional information.

http://making-security-measurable.1364806.n2.nabble.com/Record-support-in-ldap57-item-tp5874928p5874928.html

**Comment by solind** [comment]
I think I'm going to deprecate these suckers.  They really do not make sense.
