### ISSUE TITLE
spweb_object entity name correction

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#124]
The spweb_object has two entities, with the following documentation:

-- webcollectionurl - The webcollectionurl element defines the web application
to evaluate specific web settings.

-- sitecollectionurl - The sitecollectionurl element defines the site
collection to evaluate specific web settings.

I think the entities should be renamed to (and the corresponding entities
changed in the state and item):

-- sitecollectionurl – specifies a site collection

-- websiteurl – specifies a web site (this is the SPWeb object we want)

This site outlines the SharePoint object model, and has a nice diagram at the
top.  Further down the page is another diagram of the site architecture:
http://msdn.microsoft.com/en-us/library/ms473633.aspx

The important thing to note is that a Site Collection (SPSite object) contains
a tree of Web Sites (SPWeb object).

**Comment by solind** [comment]
How about we just change the documentation instead?  That's how we've handled backwards-compatibility for improperly-named entities in other cases.
