### ISSUE TITLE
WIN8/WIN2012 audit subcategories in OVAL 5.11

### ISSUE THREAD

**Issue by blakefrantz** [OVALProject/Language#136]
Windows 8 and Windows 2012 introduce new audit subcategories that do not appear to be captured in the OVAL 5.11 release planning:
http://oval.mitre.org/language/version5.11/ovaldefinition/documentation/windows-definitions-schema.html#auditeventpolicysubcategories_test

I've pulled all audit sub categories out of NTSecAPI.h in the Win 8 SDK and performed a diff against a prior version. The following items appear to be the new ones that may be good to get into OVAL 5.11. Double checking the diff would not hurt.

Please let me know if I've missed something.

Blake

---

"{0CCE9237-69AE-11D9-BED3-505054503030}": "Audit_AccountManagement_SecurityGroup_defined",
"{0CCE9238-69AE-11D9-BED3-505054503030}": "Audit_AccountManagement_DistributionGroup_defined",
"{0CCE9239-69AE-11D9-BED3-505054503030}": "Audit_AccountManagement_ApplicationGroup_defined",
"{0CCE923A-69AE-11D9-BED3-505054503030}": "Audit_AccountManagement_Others_defined",
"{0CCE923B-69AE-11D9-BED3-505054503030}": "Audit_DSAccess_DSAccess_defined",
"{0CCE923C-69AE-11D9-BED3-505054503030}": "Audit_DsAccess_AdAuditChanges_defined",
"{0CCE923D-69AE-11D9-BED3-505054503030}": "Audit_Ds_Replication_defined",
"{0CCE923E-69AE-11D9-BED3-505054503030}": "Audit_Ds_DetailedReplication_defined",
"{0CCE923F-69AE-11D9-BED3-505054503030}": "Audit_AccountLogon_CredentialValidation_defined",
"{0CCE9240-69AE-11D9-BED3-505054503030}": "Audit_AccountLogon_Kerberos_defined",
"{0CCE9241-69AE-11D9-BED3-505054503030}": "Audit_AccountLogon_Others_defined",
"{0CCE9242-69AE-11D9-BED3-505054503030}": "Audit_AccountLogon_KerbCredentialValidation_defined",
"{0CCE9243-69AE-11D9-BED3-505054503030}": "Audit_Logon_NPS_defined",
"{0CCE9245-69AE-11D9-BED3-505054503030}": "Audit_ObjectAccess_RemovableStorage_defined",
"{0CCE9246-69AE-11D9-BED3-505054503030}": "Audit_ObjectAccess_CbacStaging_defined",
"{0CCE9247-69AE-11D9-BED3-505054503030}": "Audit_Logon_Claims_defined",

**Comment by solind** [comment]
Our interpretation was that KERBEROS_TICKET_EVENTS has no mapping to a GUID -- you'll never get it.  I'll deprecate it in 5.11.2.

**Comment by wmunyan** [comment]
Also, I think there is one additional GUID introduced in Windows 10 1607:
`0CCE924A-69AE-11D9-BED3-505054503030: right_adjusted`

**Comment by solind** [comment]
I actually added that one already; it's audit_detailedtracking_tokenrightadjusted.

```
<xsd:element name="audit_detailedtracking_tokenrightadjusted" type="win-def:EntityStateAuditType" minOccurs="0">
    <xsd:annotation>
        <xsd:documentation>This subcategory audits when token privileges are enabled or disabled for a specific account’s token. This state corresponds with the following GUID specified in ntsecapi.h: 0cce924a-69ae-11d9-bed3-505054503030.</xsd:documentation>
    </xsd:annotation>
</xsd:element>
```
