### ISSUE TITLE
User and group accounts and the use of a machine qualifier in Windows Definitions

### ISSUE THREAD

**Issue by ccoffin** [OVALProject/Language#157]
OVAL Windows documentation for user_object\user, group_object\group, accesstoken_object\security_principle, and sid_object\trustee_name entities state that domain accounts be qualified with the domain name, local accounts must be qualified with a machine name, and builtin accounts need no qualifier at all. This root of this issue is #101.

There is a high level issue with this current OVAL documentation in that there is no clear language from Microsoft or any third-party on what the real differences are between a local account and a builtin account. Another side effect of this is how, or in what way tools enforce (or don't enforce) use of a qualifier.

A couple of basic ways to handle this situation. There are likely others.
a. Treat all non-domain accounts as local, regardless of whether or not they are preinstalled or user-defined. Allow these local accounts to be defined both with or without a machine qualifier?
b. Treat all non-domain accounts as local, regardless of whether or not they are preinstalled or user-defined. Force a machine qualifier on all local accounts?
c. Deprecate all constructs in current form. Separate qualifier from account using separate entities similar to sid_sid_test SC output (trustee_name and trustee_domain). This will present problems when dealing with other item entities such as user_item\group, group_item\user, and group_item\subgroup. In these sub accounts, it may not be possible to split.

**Comment by solind** [comment]
I fixed all of these in the 5.11.2 specification document.
