### ISSUE TITLE
Domain group memberships not returned for domain users in user_item\group values

### ISSUE THREAD

**Issue by ccoffin** [OVALProject/Language#162]
Nothing in the Windows documentation currently describes what kinds or groups should be returned in SC Win-sc:user_item\group entity values. It appears that ovaldi uses the NetUserGetLocalGroups API and only returns local group memberships for a given user. This is the correct behavior when local users are specified or when performing and non-equals operation on the object (i.e., patern match = .*). However, in the case that a domain user is specified in the object, only local group memberships are returned in the SC for the domain user using ovaldi. Domain group memberships are not returned. 

It would seem that the correct behavior here would be to return the local and domain group memberships when directly specifying a domain user account. This should be documented under the Win-def:user_test.

The related Win-def:group_test reports domain user and domain group memberships and qualifies them with their domain name in every case, using an equals or non-equals operation.

There is also a related ovaldi project bug number 261.

**Comment by solind** [comment]
Will update user_item/group documentation in the specification.
