### ISSUE TITLE
User and group accounts and the use of a machine qualifier in Windows System Characteristics

### ISSUE THREAD

**Issue by ccoffin** [OVALProject/Language#165]
OVAL Windows documentation for user_item\user, group_item\group, accesstoken_item\security_principle, and sid_item\trustee_name entities state that domain accounts be qualified with the domain name, local accounts must be qualified with a machine name, and builtin accounts need no qualifier at all. This root of this issue is #101. This issue is the same as #157 ecept that this tracker applies to the Windows System Characetristics while 157 applies to the Definition.

There is a high level issue with this current OVAL documentation in that there is no clear language from Microsoft or any third-party on what the real differences are between a local account and a builtin account. Another side effect of this is how, or in what way tools enforce (or don't enforce) use of a qualifier.

There needs to be a common and understood method with regard to the use of an account qualifier in the Windows System Characteristics for accounts.

some possible solutions:
- forcing the use of a qualifier in all cases, 
- allowing a qualifier to be optional (works with or without, not possible with domain accounts as it is required.),
- deprecate all current SC items and split the current account entity into two parts, one for the name and another for the domain (system or domain name).

**Comment by solind** [comment]
Fix with Issue #101
