### ISSUE TITLE
clarify the name entity documentation in the win-def:metabase_test

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#17]
We need to clarify the name entity documentation in the win-def:metabase_test.  It is not clear what values should be represented here.

Please see the following oval-developer-list post for more information.

http://making-security-measurable.1364806.n2.nabble.com/win-metabase-item-name-element-tp7579419.html

**Comment by solind** [comment]
Updating schema documentation to reflect that the name should match the constant name as defined in IIScnfg.h, which can be found in the Microsoft Windows SDK.
