### ISSUE TITLE
better explain how objects match items like what we have for state evaluation

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#173]
The section on object evaluation (matching objects to items) is not very well specified.  We should add flow charts and additional text to explain how this works much like what we have for the state evaluation section.

**Comment by solind** [comment]
I notice this has been documented in the specification, section 5.3.6.4.  There is a reference pointing to this section in section 5.3.3.3 Referencing an OVAL Variable (in part 5.3.3 OVAL Object Evaluation).  This should be sufficient clarification.
