### ISSUE TITLE
Investigate normalization of line endings

### ISSUE THREAD

**Issue by drothenberg** [OVALProject/Language#179]
Should OVAL, being commonly represented in XML, adhere to the same normalization of line endings as outlined by the current XML Recommendation (section 2.11)? This removal of the carriage return character has the potential to affect evaluation of certain file formats that contain the \r\n line ending.

**Comment by solind** [comment]
Any XML document that is required to consistently encapsulate a carriage return character must escape it.  Since OVAL documents are XML documents, it should not even be necessary to state this explicitly.  However, I will make a note of it in the specification document.
