### ISSUE TITLE
update changes that break backward compatibility to support old datatypes

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#186]
Throughout the OVAL 5.8 - 5.10.1 releases, we have made changes to entity datatypes that break backward compatibility (mostly string to int).  Those changes can be found here (http://oval.mitre.org/language/about/backwardcompatibility.html).  We should go back and update the entities to support both datatypes so that old content will not be invalid.

http://making-security-measurable.1364806.n2.nabble.com/Re-OVAL-DISCUSSION-LIST-OVAL-5-11-release-74-98-tracker-review-td7582105.html

**Comment by solind** [comment]
These were actually implemented in 5.11.
