### ISSUE TITLE
consider using xsd:nonNegativeInteger to validate DWORD values

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#192]
In various OVAL Tests for Windows, there are a few entities that are of type DWORD which represents a 32-bit unsigned integer value (http://msdn.microsoft.com/en-us/library/cc230318.aspx).  We should discuss with the community whether or not using xsd:nonNegativeInteger to enforce an unsigned value would be beneficial.

Notable entities that contain DWORD values are:

win-def:lockoutpolicy_test/lockout_duration
win-def:passwordpolicy_test/max_passwd_age

If we decide to take this approach, we should check for other occurrences.

**Comment by solind** [comment]
There would be an impact on the following STIGs, which are written to expect values of -1:
Windows Vista
Windows 2003 DC and MS
Windows 2008 DC and MS
Windows 2008 R2 DC and MS

The latest USGCB content is actually written to anticipate the ambiguity, and supports item entity values of -1 or 4294967295.

I have found no other impacted content.

**Comment by solind** [comment]
I will have to introduce new EntityStateNonNegativeIntType and EntityItemNonNegativeIntType types to enforce this.

**Comment by solind** [comment]
OK, a new type would be a bit on the intrusive side.  I think a better approach is to enforce this using schematron rules.
