### ISSUE TITLE
Complete documentation of comparing objects/states and items

### ISSUE THREAD

**Issue by chisholm** [OVALProject/Language#22]
The specification is too vague in describing object/state<->item comparisons.  It basically just tells you to use the operation in the context of the given datatype.  There is a little bit of description of nil entities and variables.

Examples of things to add:
- How to compute a result (i.e. one of the ResultEnumeration values)
- How do the various item entity status values affect results
- How do nil entities affect results
- Info regarding multiple item entities for a given object entity (ovaldi treats this as an error, should it?)

**Comment by solind** [comment]
Updating the 5.11.2 specification (section 5.3.4.1.4) to indicate the result of such an evaluation should be "not evaluated".
