### ISSUE TITLE
Incorrect Schematron rules in Mac and UNIX Schemas

### ISSUE THREAD

**Issue by drothenberg** [OVALProject/Language#235]
The unix-def:symlink_test contains a rule that inaccurately declares an element within the x-macos-def namespace.

The macos-def schema contains multiple Schematron rules with the "macos-def_macos_object_verify_filter_state" ID and several references to a "macos_object".

All of these broken rules cause errors upon validation of OVAL content.

**Comment by joval** [comment]
Oops.
