### ISSUE TITLE
moving oval-def:NotesType to OVAL Common breaks backward compatibility

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#237]
In addressing issue #6, we ended up breaking backward compatibility because we moved the NotesType construct from the OVAL Definitions Model to the OVAL Common Model.  As a result, when pre-OVAL 5.11 content is validated against OVAL 5.11, it is finding oval-def:notes and oval-def:note elements, but, is expecting oval:notes and oval:note elements.

Please see the following thread for more information.

http://making-security-measurable.1364806.n2.nabble.com/5-11-backwards-incompatibility-issue-Suspect-the-fix-for-issue-6-was-the-culprit-tp7586190.html

**Comment by mpreisler** [comment]
The following commit fixes compatibility issues in openscap. Could serve as an inspiration for OVAL 5.11.1 change addressing this.

https://github.com/OpenSCAP/openscap/commit/8e1f69c0bacb974f604f56a12da5386e1bfa8c8f

There is one issue, the change allows empty <notes> elements whereas they weren't allowed previously. I believe we can address this in schematron but I haven't implemented that yet. It could also be addressed with <xsd:assert> but we'd need to use XSD 1.1 which is not well supported.

Comments welcome.
