### ISSUE TITLE
Windows schema issue in OVAL 5.11

### ISSUE THREAD

**Issue by joval** [OVALProject/Language#243]
In the Entity[State/Item]RegistryTypeType, we should make the following changes to more accurately reflect the different possible data types in the Windows registry:
* reg_dword_little_endian should be deprecated or removed (it is defined to have the same value as reg_dword) 
* reg_qword_little_endian should be deprecated or removed (it is defined to have the same value as reg_qword)
* reg_resource_list should be added
* reg_full_resource_descriptor should be added
* reg_resource_requirements_list should be added

**Comment by drothenberg** [comment]
Initially I had only deprecated the little endian values. I plan to add the three new registry types for usability but would like to note that additional documentation should be provided wherever a value of this type may be expected, such as ntuser_*/value and registry_*/value.
