### ISSUE TITLE
Updates to Unix schema in OVAL 5.11

### ISSUE THREAD

**Issue by joval** [OVALProject/Language#244]
The following entities of the unix-def:file_state should be changed to EntityStateAnySimpleType restrictions of string/int:
* group_id
* user_id
* a_time
* c_time
* m_time

The following entities of the unix-def:password_state should be changed to EntityStateAnySimpleType restrictions of string/int:
* user_id
* group_id

The following entities of the unix-def:shadow_state should be changed to EntityStateAnySimpleType restrictions of string/int:
* chg_lst
* chg_allow
* chg_req
* exp_warn
* exp_inact
* exp_date

**Comment by drothenberg** [comment]
Shouldn't this fix also include the Item to fix backwards compatibility with OVAL 5.7 content?

Compare:
-http://oval.mitre.org/language/version5.7/ovalsc/documentation/unix-system-characteristics-schema.html#file_item
-http://oval.mitre.org/language/version5.11/ovalsc/documentation/unix-system-characteristics-schema.html#file_item

**Comment by joval** [comment]
I specifically made that exact change. Look at the 5.11.X branch of github.com/joval/jOVAL

**Comment by drothenberg** [comment]
https://raw.githubusercontent.com/joval/jOVAL/5.11.X/scap/schemas/oval-5.11/unix-definitions-schema.xsd contains changes to the restriction while https://raw.githubusercontent.com/joval/jOVAL/5.11.X/scap/schemas/oval-5.11/unix-system-characteristics-schema.xsd leaves it alone. Are you saying that it was intentionally only the unix-def that was updated?

**Comment by joval** [comment]
Yes, only the states need to be updated for backwards-compatibility of definitions files.

**Comment by joval** [comment]
Put another way, we (Joval) don't care if the s-c are backwards-compatible, only the definitions files.

Other people may care about being able to consume old s-c files, in which case yes, a corresponding change would be required.
