### ISSUE TITLE
GlobToRegexFunctionType documentation updates required

### ISSUE THREAD

**Issue by joval** [OVALProject/Language#245]
See http://making-security-measurable.1364806.n2.nabble.com/Error-in-the-schema-documentation-for-GlobToRegexFunctionType-td7586183.html#a7586394

**Comment by iankko** [comment]
Thank you for filing this ticket, David.

Further issue details (to document what is currently wrong). The current (OVAL 5.11) ```glob_to_regex()``` function documentation provides couple of examples for different values of ```noescape``` attribute. Quoting relevant parts from current documentation:
&nbsp; &nbsp;  http://oval.mitre.org/language/version5.11/ovaldefinition/documentation/oval-definitions-schema.html#GlobToRegexFunctionType

```
For example given the input glob pattern would be '\*' then the resulting Perl 5's regular
expression would be '^\\.*$' in the default (glob_noescape=false) case (here '\' would be
interpreted as an escape character), and would produce '^\.*$' in glob_noescape=true case
(since here '\' would be interpreted as an literal). Similarly the output for '\?' glob
pattern would be '^\\.$' (default,  glob_noescape=false case), and '^\.$' for
glob_noescape=true case.
```
As correctly pointed out by David via the link above, the resulting form of examples is incorrect now.

The correct version should be:
```
# Results for C '\*' glob:
----------------------------------------
  noescape | Perl regular expression
----------------------------------------
      FALSE |      ^\*$
       TRUE |     ^\\.*$
----------------------------------------

# Results for C '\?' glob:
----------------------------------------
  noescape | Perl regular expression
----------------------------------------
     FALSE |      ^\?$
      TRUE |      ^\\.$
---------------------------------------- 
```
And to provide yet one example for handling of '[' and ']' characters it's listed below:
```
# Results for C '\[hello\]' glob:
----------------------------------------
  noescape | Perl regular expression
----------------------------------------
     FALSE | ^\[hello\]$
      TRUE | ^\\[hello\\]$ 
```

I will create & attach corresponding OVAL Sandbox changes & add a diff here.

Thank you && Regards, Jan.
Jan iankko Lieskovsky
