### ISSUE TITLE
Rpm Info Item extended_name and '(none)' architecture.

### ISSUE THREAD

**Issue by Melhior** [OVALProject/Language#261]
Hello. On my Centos 7.2.1511 I have the "gpg-pubkey-f4a80eb5-53a7ff4b" package with 'none' architecture:

``` shell
[root@localhost ~]# rpm -qi gpg-pubkey-f4a80eb5-53a7ff4b
Name        : gpg-pubkey
Version     : f4a80eb5
Release     : 53a7ff4b
Architecture: (none)
```

``` shell
[root@localhost ~]# rpm -q gpg-pubkey-f4a80eb5-53a7ff4b --queryformat "%{NAME} %{ARCH}\n"
gpg-pubkey (none)
```

How we must to consider this when forming the "extended_name" element? 
Maybe the current documentation requires some additions. For example (by analogy with epoch): "Note that a null architecture (or '(none)' as returned by rpm) is equivalent to '' and would hence have the form NAME-EPOCH:VERSION-RELEASE."

What you think about that?

**Comment by solind** [comment]
According to Steve Grubb (from RedHat), the gpg-pubkey "RPM" isn't an actual RPM at all, it's a... well, he used the term "snowflake"! :)

He also said that for a normal RPM, an arch of none is not possible, and that in the context of gpg it's just meaningless.

I'll add documentation indicating that in this case the extended name should use the string "(none)" for the architecture part.
