### ISSUE TITLE
Clarification needed for linux-def:partition_state/space_left

### ISSUE THREAD

**Issue by joval** [OVALProject/Language#262]
The space_left entity should be populated with the number of blocks remaining on the device for _privileged_ users, i.e., (from statvfs.h) statvfs.f_bfree.

I also believe that we should add a new block_size entity to the item/state, which would capture the block size in bytes.  Otherwise, the block counts in the total_space, space_used and space_left entities cannot be normalized across different partitions with different block sizes.

**Comment by wmunyan** [comment]
Not a deal-breaker, but perhaps just for clarity, could the elements be named "space_left_privileged" and "space_left_unprivileged"?

Again, I'm not married to that - If it stays as is, I am OK with it.

**Comment by solind** [comment]
There is already a pre-existing space_left entity.  Renaming the original entity would break backwards-compatibility, so we'd have to deprecate it.  So, since that seemed messy, I just added a space_left_for_unprivileged_users entity.  I'm glad you say you can live with that! ;)

**Comment by wmunyan** [comment]
Understood - Totally fine!  Thanks
