### ISSUE TITLE
change HPUX trusted item element 'login_tty_u' datatype to string.

### ISSUE THREAD

**Issue by julmerII** [OVALProject/Language#270]
The schema for the HPUX trusted item has the 'login_tty_u' element datatype as an oval-sc:EntityItemIntType.  The definition of this item element is " The terminal or remote hosts associated with the last unsuccessful login to the account".  I'm pretty sure there are valid terminal and host names that are not integers. /sarc

Shouldn't the datatype for 'login_tty_u' be ' oval-sc:EntityItemStringType' just as it is for 'login_tty_s'?

**Comment by solind** [comment]
Yes, it should.
