### ISSUE TITLE
Implement SPAWAR change proposal for win-def:userright_test

### ISSUE THREAD

**Issue by solind** [OVALProject/Language#283]
Set userright_item/trustee_sid@maxOccurs to 1, and add userright_item/trustee_name and userright_state/trustee_name.

**Comment by dragosprisaca** [comment]
This change proposal breaks the backward compatibility for the Windows results\system-characteristics and introduces several challenges for the NIST SCAP Validation Program. My suggestion is to deprecate the userright test and add a new test in 5.11.2.

Respectfully,
_Dragos.

**Comment by solind** [comment]
The original request appears here:
http://lists.cisecurity.org/pipermail/oval_developer_lists.cisecurity.org/Week-of-Mon-20160118/000076.html
