### ISSUE TITLE
Schematron issues in windows and unix schemas

### ISSUE THREAD

**Issue by dragosprisaca** [OVALProject/Language#304]
The following schematron rules incorrectly fails when the source content includes a value equal to 0:

windows-definitions-schema.xsd:
Element name="force_logoff":
“<sch:assert test="string-length(.) = 0 or number(.) &lt; 0"><sch:value-of select="../@id"/> - the value of force_logoff must be greater than or equal to zero</sch:assert>”

And element name="lockout_duration":
“<sch:assert test="string-length(.) = 0 or number(.) &lt; 0"><sch:value-of select="../@id"/> - the value of lockout_duration must be greater than or equal to zero</sch:assert>”

unix-definitions-schema.xsd:
Element name="group_id":
"<sch:assert test="string-length(.) = 0 or number(.) &lt; 0"><sch:value-of select="../@id"/> - the value of group_id must be greater than zero</sch:assert>"

Element name="user_id":
"<sch:assert test="string-length(.) = 0 or number(.) &lt; 0"><sch:value-of select="../@id"/> - the value of user_id must be greater than zero</sch:assert>"

Thanks,
_Dragos.

**Comment by solind** [comment]
I agree, and I'm going to close this issue as a duplicate to #302.
