### ISSUE TITLE
Add getent-{test, object, state}

### ISSUE THREAD

**Issue by redhatrises** [OVALProject/Language#305]
Currently, there is no easy way (at least on a Linux system) to query multiple password databases. As Linux (there might be others) contains the `getent` command, this command would equally be of good use to check password configurations for multiple password databases for users of a system (e.g. `/etc/passwd`, LDAP, etc.)

**Comment by wmunyan** [comment]
I'll concur with @solind, and note that CIS-CAT also uses `getent` for both password_object collection and shadow_object collection.  CIS-CAT's "backup" plan for any case that `getent` is not available, is to directly check `/etc/passwd` and `/etc/shadow`

**Comment by redhatrises** [comment]
Thanks @solind and @wmunyan 

Am I just getting caught up in the language that says that password_{test, object, state} is checking `/etc/passwd`, and that it uses the `passwd` command? Seems very distinctive usage of `/etc/passwd` and `passwd` command with no mention of `getent` or that using `getent` is okay.

```
< password_test >

/etc/passwd. See passwd(4).

The password test is used to check metadata associated with the UNIX password file, of the sort returned by the passwd command. It extends the standard TestType as defined in the oval-definitions-schema and one should refer to the TestType description for more information. The required object element references a password_object and the optional state element specifies the metadata to check. 
```

**Comment by solind** [comment]
Indeed, @redhatrises, look at that! ;)

At a minimum we should update the documentation for the password_test, to reflect what I think most interpreters are doing (i.e., using getent).

If one wants to explicitly check only /etc/passwd, one could use a textfilecontent_test.

**Comment by redhatrises** [comment]
> At a minimum we should update the documentation for the password_test, to reflect what I think most interpreters are doing (i.e., using getent).

@solind that would be awesome!
