### ISSUE TITLE
make win-def:cmdlet_test parameter fields nillable

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#38]
We should make the win-def:cmdlet_test parameter fields nillable to represent switch parameters which have no value (http://msdn.microsoft.com/en-us/library/windows/desktop/dd878252(v=vs.85).aspx).

Please see the following oval-developer-list post for additional information.

http://making-security-measurable.1364806.n2.nabble.com/win-cmdlet-test-change-for-OVAL-5-11-tp7579519.html

**Comment by solind** [comment]
It appears this change has been made already (as of 5.11.1).
