### ISSUE TITLE
investigate the ability to cast entities to different datatypes

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#48]
The ability to cast entities to a different datatype could be a useful capability when trying to check the state of a system.  We should investigate this topic further.  Please see the following oval-developer-list post for additional information.

http://making-security-measurable.1364806.n2.nabble.com/OVAL-5-8-s-rework-of-the-datatype-attribute-td6099259.html

This topic was further discussed here:

http://making-security-measurable.1364806.n2.nabble.com/OVAL-Selected-Issues-Entity-Casting-tp6520654p6520654.html

**Comment by solind** [comment]
Currently the OVAL language permits arbitrary casting through variables, so perhaps this change has languished because it's been unnecessary.  Closing.
