### ISSUE TITLE
should the command_line entity be nillable in the Windows process tests?

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#57]
On Windows, there are a few special processes (Idl, System, etc.) that do not have command lines associated with them.  Should we make these entities nillable?  Right now, content authors and tools are left to just specify an empty string.  

Please see the following oval-developer-list post for additional information.

http://making-security-measurable.1364806.n2.nabble.com/Windows-process58-item-Question-tp7580331.html

**Comment by solind** [comment]
Assigning to 5.11.2.
