### ISSUE TITLE
fix inconsistencies between the diagrams and tables in the specification

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#58]
It looks like the oval-def:CriteriaType and oval-res:CriteriaType constructs are not consistent in the information displayed by the tables (i.e. oval-def:CriteriaType has all properties in the table including extend_definition, criteria, and criterion whereas oval-res:CriteriaType only has criteria).  These should be brought into alignment and we should also check for other inconsistencies between the tables and diagrams.

Please see the following oval-developer-list post for additional information.

http://making-security-measurable.1364806.n2.nabble.com/OVAL-Language-Specification-01-20-2012-Typos-tp7580573.html

**Comment by solind** [comment]
I take this to mean the child entities appearing in the table of properties should be removed (as they are not properties), and replaced with some descriptive text in both locations.  The accompanying class diagrams are correct.
