### ISSUE TITLE
Fix contradictions regarding how to assign status values to items and item entities.

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#69]
The OVAL spec seems contradictory about what to do [when there is an error
during collection].  Something should get status=error, but it's not clear
what.  5.2.4.4 says you should use status=error on the item if "... there
is an error that prevents the collection of an OVAL Item or any of its
entities."  On the other hand, 5.2.4.5.2 says that item entity status
"... SHOULD NOT be propagated up to the containing OVAL Item."

It looks like the schema documentation for oval-sc:ItemType also seems to
contradict itself.  I surrounded the important parts with ***.

From oval-sc:ItemType:

"The required status attribute holds information regarding the success of
the data collection. For example, if an item exists on the system then the
status would reflect this with a value of 'exists'. **_If there was an error
collecting any information about an item that is known to exist, then the
status would be 'error'. An error specific to a particular entity should be
addressed at the entity level and not the item level.**_ When creating items,
any entities that can successfully be collected should be reported."

From oval-sc:StatusEnumeration, the last sentence is incorrect:

"A status of 'error' says that there was an error collecting information
associated with an item as a whole or a specific entity. An item would have a
status of 'error' if a problem occurred that prevented the item from being
collected. For example, a file_item would have a status of 'error' if a handle
to the file could not be opened because the handle was already in use by
another program.  Also, if an item has entities with a status of 'error' and
entities with a status of 'exists', the status of 'error' must not be
propagated up to the item level as the item may still be usable."

The following is how errors should be handled; the above parts of the spec (and
any other contradictory/vague/ambiguous parts we may have missed) need to be
clarified to agree with this policy:
- If collection is being done based on an object
  - If collecting an item which could match the object
    - If an error occurs which is not associated with any of the item entities,
      create the item with status=error.
  - If an error occurs which is associated with an item entity
    o ... which matches an object entity, create the item with status=error,
    and also assign status=error to the item entity.
    o ... which doesn't match an object entity, assign status=error to the
    item entity, but not the item.
  - If an error occurs while identifying items to be collected, and is not
    associated with any particular item
  - Assign flag=error to the collected_object. 
- If collection is not being done based on an object
  - The first "+" bullet above always applies, because any object
    might be used to match against the collected items.

The basic idea is that an error may or may not be associated with a particular
item, and if it is, it may or may not be associated with a particular item
entity.  All bases need to be covered.

In the first "+" bullet, the word "could" is important,
because it's important to make sure the state of a system is not
misrepresented.  If the error prevents you from knowing whether the item
matches the object, you need to report that.  Ignoring an item which would have
matched had the error not occurred, is bad.

**Comment by solind** [comment]
Will address in 5.11.2
