### ISSUE TITLE
is there a need to update the ind-def:xmlfilecontent_test?

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#70]
Is there a need to update the ind-def:xmlfilecontent_test to expand support for
what can be collected?

Right now, the ind-def:xmlfilecontent_test is limited to collecting text-node
and attribute values.

**Comment by solind** [comment]
The test seems to be serving the community well.  Let's close, and see if a use-case-specific enhancement request is ever raised pertaining to it.
