### ISSUE TITLE
Re-examine whether to include regular expression modifiers

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#72]
The list of libraries previously surveyed, which can be found on the
"Regular Expression Support"
page(http://oval.mitre.org/language/about/re_support_5.6.html) are listed
below, with a reference to their ability to support the case insensitive
modifier.

.NET - http://msdn.microsoft.com/en-us/library/yd1hzczs.aspx
BOOST -
http://www.boost.org/doc/libs/1_34_1/libs/regex/doc/syntax_perl.html#Perl
Java - http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html
JavaScript - http://www.w3schools.com/jsref/jsref_regexp_i.asp
PCRE - http://php.net/manual/en/reference.pcre.pattern.modifiers.php
Perl 5.004 - http://perldoc.perl.org/perlre.html#Extended-Patterns
Python - http://docs.python.org/library/re.html

All surveyed libraries except JavaScript support the “?i” modifier flag,
but JavaScript still supports it via another method.

**Comment by solind** [comment]
Let's do it.
