### ISSUE TITLE
Update documentation for deprecated check="none exist" enumeration

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#73]
With the deprecation of the "none exist" check attribute, it is
unclear that in addition to remapping to check="none satisfy", one
should also remap the check_existence attribute to "none_exist".
Currently only the check attribute is mentioned in the documentation. This
leads to confusion when an existing check_existence attribute gets overwritten
when using the deprecated check value.

Original discussion about the topic:
http://making-security-measurable.1364806.n2.nabble.com/Mapping-Version-5-3-check-existence-and-check-state-to-previous-5-x-releases-tp23351p23352.html

**Comment by solind** [comment]
Declaring this a duplicate of Issue #7
