### ISSUE TITLE
we should clarify the documentation of the unix-def:shadow_test/flag entity

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#74]
We should clarify the documentation of the unix-def:shadow_test/flag entity to
state that the value should be a numeric value.

Please see the following links for additional information.

Structure of Password File
http://tldp.org/HOWTO/Shadow-Password-HOWTO-8.html

Shadow Password File Man Page
http://www.lehman.cuny.edu/cgi-bin/man-cgi?shadow+4

**Comment by solind** [comment]
This will be fixed by creating an inline complexType, just like the password_item/userid entity was.
