### ISSUE TITLE
are evr_string documentation updates needed?

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#75]
The evr_string datatype is used for rpm and dpkg EVR strings. Currently, the
documentation states that we should use the rpmvercmp() function to perform the
comparison. However, I am not sure if using that function is valid for comparing
dpkg EVR strings or if some other function should be used. Anyways, it is
something that we should look into and clarify in the documentation as
necessary.

DPKG EVR Documentation
http://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version

It also looks like newer versions of librpm have code to compare dpkg EVR
strings (see lib/rpmdpkg.h) so maybe there are differences.

RPM 4.5 Documentation
http://rpm5.org/docs/api/files.html

We should also see how the dpkg code does the comparisons.

**Comment by solind** [comment]
This was addressed with the addition of the debian_evr_string datatype.
