### ISSUE TITLE
change how regex_capture function behaves when no matches are found

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#78]
There has been a request to consider changing the behavior of the regex_capture
function so that it returns zero values instead of an empty string when no
matches are found. This will require making a new version of the function as it
will break existing content written to check for the empty string.

Please see the following oval-developer-list post for additional information.

http://making-security-measurable.1364806.n2.nabble.com/Path-Datatypes-in-OVAL-tp7578604.html

**Comment by solind** [comment]
I think this was not a good idea, and since it was my idea to begin with, I'll just close it! :)
