### ISSUE TITLE
specify how to handle redirection on content created before OVAL 5.10

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#79]
We need to specify how to handle redirection on content created before OVAL 5.10
because the windows_view behavior is not available.

**Comment by solind** [comment]
Wouldn't old content simply be expected to take on the default value?  (i.e., 64-bit view, applicable only to 64-bit systems?)  In other words, don't we design default values specifically for backwards-compatibility?

Anyway where would this be defined?  In the Windows component schema specification document?
