### ISSUE TITLE
Reevaluate whether foreign_* entities are appropriate on win-def:port_test

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#81]
http://making-security-measurable.1364806.n2.nabble.com/OVAL-Version-4-Schema-Issues-tp22326.html

has a nice discussion about the nature of the port_test.  It seems to have been
decided there that the most important thing was open "listening"
ports, i.e. UDP ports and TCP server ports.  Here, foreign addresses/ports are
not relevant.

http://making-security-measurable.1364806.n2.nabble.com/Windows-port-test-and-foreign-address-tp5009123.html

was where it was decided to add the foreign_address and foreign_port entities. 
This doesn't seem to jive with the original intent of the test.  We need to
determine whether the foreign_\* entities really make sense, and clarify the
schema documentation depending on what we decide.

Issues with the current schema docs include:

foreign_address

"This is the IP address with which the program is communicating, or with
which it will communicate, in the case of a listening server. Note that the IP
address can be IPv4 or IPv6."

This doesn't make sense, since (a) you can't tell which server a listening port
will be communicating with, and (b) you can't get remote info for UDP ports on
windows.  At least, I didn't see any in the MIB_UDBTABLE_\* structures.

foreign_port

"This is the TCP or UDP port to which the program communicates."

There is no remote port for UDP, since there are no connections (UDP is
connectionless).

Also, a lot of the documentation mentions "listening" ports, but it
is not clear whether you are to only include UDP and server TCP ports, or info
about established TCP connections as well.  "Listening" implies the
former, but the fact that there are foreign_\* entities implies the latter. 
Details
http://making-security-measurable.1364806.n2.nabble.com/OVAL-Version-4-Schema-Issues-tp22326.html

has a nice discussion about the nature of the port_test.  It seems to have been decided there that the most important thing was open "listening" ports, i.e. UDP ports and TCP server ports.  Here, foreign addresses/ports are not relevant.

http://making-security-measurable.1364806.n2.nabble.com/Windows-port-test-and-foreign-address-tp5009123.html

was where it was decided to add the foreign_address and foreign_port entities.  This doesn't seem to jive with the original intent of the test.  We need to determine whether the foreign_\* entities really make sense, and clarify the schema documentation depending on what we decide.

Issues with the current schema docs include:

foreign_address

"This is the IP address with which the program is communicating, or with which it will communicate, in the case of a listening server. Note that the IP address can be IPv4 or IPv6."

This doesn't make sense, since (a) you can't tell which server a listening port will be communicating with, and (b) you can't get remote info for UDP ports on windows.  At least, I didn't see any in the MIB_UDBTABLE_\* structures.

foreign_port

"This is the TCP or UDP port to which the program communicates."

There is no remote port for UDP, since there are no connections (UDP is connectionless).

Also, a lot of the documentation mentions "listening" ports, but it is not clear whether you are to only include UDP and server TCP ports, or info about established TCP connections as well.  "Listening" implies the former, but the fact that there are foreign_\* entities implies the latter.

**Comment by solind** [comment]
This test looks like the Windows version of the MacOS inetlisteningserver[s][510] test.  So, let's treat it exactly the same, and document that the foreign_port value should be '0' for a listening process.
