### ISSUE TITLE
Incorrect evaluation of "at_least_one_exists" existence check

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#82]
Currently the "at_least_one_exists" ExistenceEnumeration value does
not properly support a case where no items are collected. The evaluation for
returning false should be switched from "1 or more does not exist
items" to "0 or more does not exist items" to account for this.

**Comment by solind** [comment]
Found an original contemporaneous discussion related to this issue:
http://making-security-measurable.1364806.n2.nabble.com/Partial-Matching-in-OVAL-td7578506.html
