### ISSUE TITLE
Need to fix how check_existence works

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#83]
The general problem is that the language rules surrounding the check_existence
attribute on tests, and the optionality of partial match items, is
contradictory.  The check_existence enumerator value "all_exist" will
cause the test result to change based on the existence of partial match items,
which means those items are not ignored when evaluating tests.  So they are not
really "optional" in that sense.

The _only_ time an item has status="does not exist" is when that item
represents a partial match, in which case it should be ignored during
evaluation.  Partial matches may be included for informational purposes only. 
So the tables in the documentation for ExistenceEnumeration need to have the
"DE" columns removed.  

Also, the "all_exist" enumerator can't be interpreted sensibly.  In
general, you can't know what should have been collected, so you can't compare
that against what was actually collected to determine whether you got
everything.  In the absence of errors, and ignoring bugs, whatever the scanner
found must be interpreted to be all there was to find.  So if you found
anything at all, you must assume "all_exist" is true.  But that is
effectively the same behavior as for the "at_least_one_exists"
enumerator.  So "all_exist" is redundant and it should be removed.

If this can't be done for reasons of backward compatibility, the all_exist
enumerator should be deprecated, or at least the documentation updated to urge
content authors not to use it.  (And of course we could choose to deprecate
at_least_one_exists and keep all_exist... either works.)

**Comment by solind** [comment]
Everything above is true, however, "all_exist" actually does make sense in the context of the check_existence attribute added to EntityStateSimpleBaseType and EntityStateComplexBaseType in OVAL 5.11.  The DE entries in the truth tables also remain relevant for this use-case. Therefore, all_exist should not be deprecated.

We should add documentation noting its irrelevance outside of an OVAL State Entity check_existence evaluation.
