### ISSUE TITLE
determine if the win-def:metabase_test needs to be updated

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#84]
We need to determine if the win-def:metabase_test needs to be updated to
accomodate the changes made in IIS 7.0.

http://mvolo.com/blogs/serverside/archive/2007/07/21/Anatomy-of-an-IIS7-configuration-path.aspx

Please see the following oval-developer-list for more information.

http://making-security-measurable.1364806.n2.nabble.com/Proposed-modification-to-the-plist510-test-in-the-Apple-Macintosh-Schema-tp7471496p7471496.html

**Comment by solind** [comment]
I don't believe it does need to be updated, as IIS7 uses config files.  The metabase is dead!  (We will keep legacy support, of course).
