### ISSUE TITLE
is support for the HKEY_CURRENT_USER_LOCAL_SETTINGS hive needed in the Windows registry-based tests? 

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Language#97]
A new hive in Windows 7, HKEY_CURRENT_USER_LOCAL_SETTINGS, is not accounted for
in win-def:Entity(Object|State)RegistryHiveType or
win-sc:EntityItemRegistryHiveType. Should it be? 

See http://msdn.microsoft.com/en-us/library/ms724836(v=VS.85).aspx, as well as
the community content on the same page, which talks about the role of 
HKEY_CURRENT_USER_LOCAL_SETTINGS when using roaming profiles within a domain.

**Comment by sumanthr2810** [comment]
Do we have any oval test content for HKEY_CURRENT_USER_LOCAL_SETTINGS?

**Comment by solind** [comment]
I'm not aware of any.
